In [1]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/


1. Загрузите данные close_prices.csv. В этом файле приведены цены
акций 30 компаний на закрытии торгов за каждый день периода.
2. На загруженных данных обучите преобразование PCA с числом
компоненты равным 10. Скольких компонент хватит, чтобы объяснить 90% дисперсии?
3. Примените построенное преобразование к исходным данным и возьмите значения первой компоненты.
4. Загрузите информацию об индексе Доу-Джонса из файла djia_prices.csv.
Чему равна корреляция Пирсона между первой компонентой и индексом Доу-Джонса?
5. Какая компания имеет наибольший вес в первой компоненте?

In [5]:
!ls /content/gdrive/MyDrive/ML/

classification.csv  djia_index.csv	 perceptron-train.csv  svm-data.csv
close_prices.csv    housing.data	 salary-test-mini.csv  titanic.csv
comments.csv	    housing.names	 salary-train.csv      wine.data
data-logistic.csv   perceptron-test.csv  scores.csv	       wine.names


In [40]:
import pandas as pd
import numpy as np

from sklearn.decomposition import PCA

In [41]:
data = pd.read_csv('/content/gdrive/MyDrive/ML/close_prices.csv')

In [42]:
print(data.shape)
data.head(5)

(374, 31)


date        AXP          BA        CAT       CSCO         CVX  \
0  2013-09-23  76.440002  117.510002  85.029999  24.270000  125.519997   
1  2013-09-24  76.070000  119.000000  85.110001  24.139999  124.489998   
2  2013-09-25  75.989998  118.510002  84.500000  24.430000  124.070000   
3  2013-09-26  76.320000  119.379997  84.199997  23.770000  123.489998   
4  2013-09-27  75.889999  118.739998  83.800003  23.330000  122.639999   

          DD        DIS         GE          GS  ...        PFE         PG  \
0  59.409999  64.750000  24.280001  165.250000  ...  28.799999  79.279999   
1  59.319997  64.320000  24.320000  162.970001  ...  28.709999  78.620003   
2  59.319997  64.449997  24.230000  162.309998  ...  28.490000  77.720001   
3  59.509996  65.239998  24.250000  162.289993  ...  28.520000  78.050003   
4  59.009995  65.190002  24.049999  159.850006  ...  28.879999  77.209999   

           T        TRV        UNH         UTX           V         VZ  \
0  34.220001  86.379997  71.820000  109.419998  196.240005  47.980000   
1  34.090000  85.870003  72.320000  110.000000  193.339996  47.270000   
2  34.049999  85.980003  71.980003  109.260002  191.559998  46.950001   
3  34.230000  85.830002  72.160004  109.660004  193.559998  47.669998   
4  33.980000  85.410004  71.989998  109.360001  193.050003  47.000000   

         WMT        XOM  
0  76.419998  87.750000  
1  75.750000  87.360001  
2  74.650002  87.139999  
3  74.620003  87.070000  
4  74.360001  86.900002  

[5 rows x 31 columns]

In [43]:
model = PCA(n_components=10)
transformed_data = model.fit_transform(data.loc[:,'AXP':'XOM'])

In [44]:
model.explained_variance_ratio_

array([0.73897118, 0.11007169, 0.04995088, 0.0287492 , 0.02215448,
       0.01931577, 0.00674853, 0.00614091, 0.00320594, 0.00305611])

4 компоненты достаточно для объяснения 90% дисперсии (при 3 компонетах 89.899%)

In [45]:
model.explained_variance_ratio_

array([0.73897118, 0.11007169, 0.04995088, 0.0287492 , 0.02215448,
       0.01931577, 0.00674853, 0.00614091, 0.00320594, 0.00305611])

In [46]:
data = pd.read_csv('/content/gdrive/MyDrive/ML/djia_index.csv')

In [47]:
dataDJ.head(5)

date          ^DJI
0  2013-09-23  15401.379883
1  2013-09-24  15334.589844
2  2013-09-25  15273.259766
3  2013-09-26  15328.299805
4  2013-09-27  15258.240234

In [48]:
corr = np.corrcoef(transformed_data[:,0], dataDJ['^DJI'])

In [49]:
print(corr) # корреляция Пирсона 

[[1.         0.90965222]
 [0.90965222 1.        ]]


In [50]:
#company = data.keys()[model.components_[0].argmax()]
company = data.keys()[abs(model.components_[0]).argmax() + 1]
print(company)

V


V: Это сокращенное название компании Visa, которая идет сразу за UTX